name: Patch Request
description: Request a functional patch for the application
labels: ["patch request"]
body:
  - type: textarea
    attributes:
      label: Patch Description
      description: What functionality does this patch provide and why is it needed?
      placeholder: |
        • Problem being solved
        • Expected behavior after patch
        • Use case examples
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Device Compatibility
      description: Which devices should support this patch?
      options:
        - All Android devices
        - Specific manufacturers only
        - Selected device models only
    validations:
      required: true

  - type: textarea
    attributes:
      label: Implementation Suggestions
      description: |
        How could this be implemented? (Optional technical suggestions)
        • ADB commands
        • System settings modifications
        • Configuration changes
      placeholder: |
        Example implementations:
        - ADB: `adb shell settings put global setting_name value`
        - Modify: /system/build.prop
        - Toggle: Settings.Secure.FLAG_NAME

  - type: checkboxes
    attributes:
      label: Requirements info
      options:
        - label: This patch requires root access?
          required: false
